#pragma once

#include "tusb_option.h"

#define CFG_TUSB_MCU OPT_MCU_RP2040
#define CFG_TUSB_OS OPT_OS_PICO
#define BOARD_TUD_RHPORT 0
#define BOARD_TUH_RHPORT 1
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE)
#define CFG_TUSB_RHPORT1_MODE (OPT_MODE_HOST)
#define CFG_TUH_RPI_PIO_USB 1

#define CFG_TUD_ENDPOINT0_SIZE 64

#define CFG_TUD_CDC 0
#define CFG_TUD_MSC 0
#define CFG_TUD_HID 4
#define CFG_TUD_MIDI 0
#define CFG_TUD_VENDOR 0

#define CFG_TUD_HID_EP_BUFSIZE 64

#define CFG_TUH_ENUMERATION_BUFSIZE 512
#define CFG_TUH_DEVICE_MAX 1
#define CFG_TUH_HUB 0
#define CFG_TUH_HID 4
#define CFG_TUH_HID_EPIN_BUFSIZE 64
