#pragma once

#include <stdint.h>

#define KEYREMAP_REPORT_SIZE 64
#define KEYREMAP_PROTOCOL_MAJOR 2
#define KEYREMAP_PROTOCOL_MINOR 0

enum {
  CMD_GET_INFO = 0x01,
  CMD_SET_LED = 0x02,
  CMD_GET_CONFIG_SUMMARY = 0x10,
  CMD_GET_BINDING = 0x11,
  CMD_SET_BINDING = 0x12,
  CMD_SAVE_CONFIG = 0x13,
  CMD_RESET_CONFIG = 0x14,
  CMD_GET_RAW_REPORTS = 0x20,
  CMD_GET_HID_INTERFACES = 0x21,
  CMD_GET_REPORT_DESCRIPTOR = 0x22,
  CMD_SET_ACTIVE_LAYER = 0x30,
  CMD_GET_LAYER_STATE = 0x31,
  CMD_GET_HOST_STATUS = 0x32,
  CMD_GET_EVENT_LOG = 0x34,
  CMD_SIMULATE_INPUT = 0x40,
  CMD_RELEASE_ALL = 0x42,
  CMD_REBOOT_BOOTSEL = 0x7f,
};

enum {
  STATUS_OK = 0x00,
  STATUS_UNKNOWN_COMMAND = 0x01,
  STATUS_INVALID_LENGTH = 0x02,
  STATUS_BUSY = 0x03,
  STATUS_INTERNAL_ERROR = 0x04,
};

enum {
  INPUT_KIND_KEY = 0x01,
  INPUT_KIND_MOUSE_BUTTON = 0x02,
  INPUT_KIND_REL_X = 0x03,
  INPUT_KIND_REL_Y = 0x04,
  INPUT_KIND_WHEEL = 0x05,
  INPUT_KIND_CONSUMER = 0x06,
};

enum {
  OUTPUT_KIND_NONE = 0x00,
  OUTPUT_KIND_KEY = 0x01,
  OUTPUT_KIND_MOUSE_BUTTON = 0x02,
  OUTPUT_KIND_REL_X = 0x03,
  OUTPUT_KIND_REL_Y = 0x04,
  OUTPUT_KIND_WHEEL = 0x05,
  OUTPUT_KIND_LAYER = 0x06,
  OUTPUT_KIND_CONSUMER = 0x07,
  OUTPUT_KIND_NEXT_LAYER = 0x08,
  OUTPUT_KIND_LAYER_HOLD = 0x09,
  OUTPUT_KIND_BLOCK = 0x0a,
};
